<?php

namespace StockBundle\Repository;

/**
 * StockSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
