<?php

namespace StockBundle\Repository;

/**
 * TrendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrendRepository extends \Doctrine\ORM\EntityRepository
{
}
