<?php

namespace StockBundle\Repository;

/**
 * TrendSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrendSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
